In [ ]:
import numpy as np
#基本数乘操作

# 使用 numpy.multiply 实现数乘
vector = np.array([1, 2, 3])
scalar = 3
result = np.multiply(vector, scalar)
print(f"原向量: {vector}")
print(f"标量: {scalar}")
print(f"数乘结果: {result}")  # 输出: [3 6 9]

# 也可以直接使用 * 运算符
result2 = vector * scalar
print(f"使用 * 运算符: {result2}")  # 输出: [3 6 9]

原向量: [1 2 3]
标量: 3
数乘结果: [3 6 9]
使用 * 运算符: [3 6 9]


In [ ]:
import numpy as np
#不同维度向量的数乘

# 二维向量数乘
vector_2d = np.array([[1, 2], [3, 4]])
scalar = 2
result_2d = np.multiply(vector_2d, scalar)
print(f"二维向量:\n{vector_2d}")
print(f"数乘结果:\n{result_2d}")
# 输出:
# 二维向量:
# [[1 2]
#  [3 4]]
# 数乘结果:
# [[2 4]
#  [6 8]]

# 三维向量数乘
vector_3d = np.array([1, 2, 3, 4, 5])
scalar = -2
result_3d = np.multiply(vector_3d, scalar)
print(f"三维向量: {vector_3d}")
print(f"数乘结果: {result_3d}")  # 输出: [-2 -4 -6 -8 -10]

二维向量:
[[1 2]
 [3 4]]
数乘结果:
[[2 4]
 [6 8]]
三维向量: [1 2 3 4 5]
数乘结果: [ -2  -4  -6  -8 -10]


In [3]:
import numpy as np

# 向量与多个标量的广播数乘
vector = np.array([1, 2, 3])
scalars = np.array([2, 3, 4])
result = np.multiply(vector, scalars)
print(f"向量: {vector}")
print(f"标量数组: {scalars}")
print(f"广播数乘结果: {result}")  # 输出: [ 2  6 12]

# 列向量与行标量的广播数乘
vector_col = np.array([[1], [2], [3]])  # 3x1 列向量
scalars_row = np.array([2, 3, 4])       # 1x3 行标量
result_broadcast = np.multiply(vector_col, scalars_row)
print(f"列向量:\n{vector_col}")
print(f"行标量: {scalars_row}")
print(f"广播数乘结果:\n{result_broadcast}")
# 输出:
# 列向量:
# [[1]
#  [2]
#  [3]]
# 行标量: [2 3 4]
# 广播数乘结果:
# [[ 2  3  4]
#  [ 4  6  8]
#  [ 6  9 12]]

向量: [1 2 3]
标量数组: [2 3 4]
广播数乘结果: [ 2  6 12]
列向量:
[[1]
 [2]
 [3]]
行标量: [2 3 4]
广播数乘结果:
[[ 2  3  4]
 [ 4  6  8]
 [ 6  9 12]]


In [4]:
import numpy as np
#使用 out 参数进行数乘

# 使用预分配数组存储结果
vector = np.array([1.0, 2.0, 3.0])
scalar = 2.5
output = np.empty_like(vector)
result = np.multiply(vector, scalar, out=output)
print(f"数乘结果: {result}")
print(f"输出数组: {output}")
# 输出:
# 数乘结果: [2.5 5.  7.5]
# 输出数组: [2.5 5.  7.5]

数乘结果: [2.5 5.  7.5]
输出数组: [2.5 5.  7.5]


In [5]:
import numpy as np

# 验证数乘的数学性质
vector = np.array([1, 2, 3])
a, b = 2, 3

# 分配律: (a + b) * vector = a * vector + b * vector
left_side = np.multiply((a + b), vector)
right_side = np.add(np.multiply(a, vector), np.multiply(b, vector))
print(f"分配律验证:")
print(f"(a + b) * vector = {left_side}")      # [5 10 15]
print(f"a * vector + b * vector = {right_side}")  # [5 10 15]
print(f"是否相等: {np.array_equal(left_side, right_side)}")  # True

# 结合律: (a * b) * vector = a * (b * vector)
left_side2 = np.multiply((a * b), vector)
right_side2 = np.multiply(a, np.multiply(b, vector))
print(f"\n结合律验证:")
print(f"(a * b) * vector = {left_side2}")        # [6 12 18]
print(f"a * (b * vector) = {right_side2}")       # [6 12 18]
print(f"是否相等: {np.array_equal(left_side2, right_side2)}")  # True

分配律验证:
(a + b) * vector = [ 5 10 15]
a * vector + b * vector = [ 5 10 15]
是否相等: True

结合律验证:
(a * b) * vector = [ 6 12 18]
a * (b * vector) = [ 6 12 18]
是否相等: True
